= The Fortuna Academy for Thaumaturgical Education
Chris L. Barnes <chrislloydbarnes@gmail.com>
:toc: left
:!player-only:

_The Fortuna Academy for Thaumaturgical Education_ ("_Fortuna's_") is a tabletop role-playing game, where you play a young character attending a school for magic users.
If you enjoy books like https://www.penguinrandomhouse.com/series/WWI/worst-witch[the Worst Witch] and https://www.wizardingworld.com/[Harry Potter], TV shows like https://www.imdb.com/title/tt4254242/[The Magicians], and games like https://renegadegamestudios.com/kids-on-brooms/[Kids On Brooms], this may be for you!

_Fortuna's_ is based on the https://evilhat.com/product/fate-condensed/[Fate Condensed] system, for easy-to-start, hard-to-stop games full of competent, proactive, and dramatic characters.
The _Fortuna's_ experience is one of collaborative storytelling rather than linear number-crunching.

== Setting

Thaumaturges (users of magic) exist in a reality almost parallel to our own mundane one.
They can see and do everything we can (although their auras tend to interfere with electronic devices), as well as interacting with a host of other planes, places, creatures, and characters.
Even among this mysterious community, the Fortuna Academy for Thaumaturgical Education, colloquially referred to as Fortuna's, is a mystery unto itself.
Arch-witch Ms Fortuna has presided over the boarding school for as long as anyone can remember, and while her former students are scattered throughout the magical world, few can put together more than a handful of the Academy's secrets.

Fortuna's students come from a wide geographical region, as the Academy itself seems to have no fixed location: some alumni recall seeing the same scenery for their entire tenure, while others report awaking to misty moors, frosty peaks, dense jungles, and even a horizon of unbroken ocean on different occasions.
Thaumaturges' magical backgrounds are even more diverse.
Students range from scions of storied magical bloodlines, to Mundanes who dug too deep into the darkest corners of the library.
Dragons trapped in humanoid form, descendants of celestials, revenants who have bargained with Those Below, heirs to elven thrones, and cursed puppets have all called Fortuna's their alma mater.

Nobody knows how Ms Fortuna selects or even identifies prospective students, but the prestige of the Academy is such that few ever turn down an invitation.
Students simply receive a communication bearing the legendary heading _curiosos Fortuna iuvat_, with instructions on how and when to enter the Academy.
On the first Tuesday after the southward equinox, term begins.

== Rules

Players roll a six-sided die.
The highest roll wins!

ifndef::player-only[]

== Game Master rules

Actually, the person with the best voice acting may win.

endif::player-only[]

:leveloffset: +1

include::CREDITS.adoc[]

include::LICENSE.adoc[]

:leveloffset: -1
