name: CI

on: [push, pull_request]

permissions:
  contents: write

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.1"
        bundler-cache: true
    - run: bundle exec rake
      name: Build documents
    - name: Deploy to GH pages
      # if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: build/html
    - name: Compress HTML artifacts
      run: |
        zip -r build/html.zip build/html
        tar cf - build/html/ | xz -z - > build/html.tar.xz
    - name: Make GH release if tagged
      if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/html.*
          build/index.*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
